
export enum VorgangBearbeitenSchritt {
    MITARBEITER_AUSWAHL   = "MITARBEITER_AUSWAHL",
    BKZ_AUSWAHL           = "BKZ_AUSWAHL",
    STANDARD_HARDWARE     = "STANDARD_HARDWARE",
    INDIVIDUAL_BESTELLUNG = "INDIVIDUAL_BESTELLUNG",
    ABHOLUNG              = "ABHOLUNG",
    LIEFERANSCHRIFT       = "LIEFERANSCHRIFT",
    GENEHMIGUNG           = "GENEHMIGUNG",
    ABSCHLUSS             = "ABSCHLUSS",
}
